apiVersion: v1
kind: Service
metadata:
  name: eks-app-service
spec:
  selector:
    app.kubernetes.io/name: eks-app-application
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31080
    port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-servicet
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-app-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-app-application
    spec:
      containers:
      - name: app-argocd-container
        image: 343218222789.dkr.ecr.ap-northeast-2.amazonaws.com/eks-second:0701449834c7d4910eb40e8252192f567263373a
        ports:
          - protocol: TCP
            containerPort: 8080
